// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'Failed to get Firebase options for your platform. '
          'You must configure Firebase options manually.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv8PdVywhE-TPttEG7un0DWhF-PWdQBkA',
    appId: '1:379198043128:web:3bf49e6406fc7e2f75dc0d',
    messagingSenderId: '379198043128',
    projectId: 'shift-c35b1',
    authDomain: 'shift-c35b1.firebaseapp.com',
    storageBucket: 'shift-c35b1.appspot.com',
    measurementId: 'G-YGX80HY6WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR0mcCkUWZZXfL3Xj0xEQdo0Q3DyLM3Jo',
    appId: '1:379198043128:android:2ea5bf3d73b0a86a75dc0d',
    messagingSenderId: '379198043128',
    projectId: 'shift-c35b1',
    storageBucket: 'shift-c35b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjI9Z-LdL8IYLQtlqAStSoc9EW7fvLWKw',
    appId: '1:379198043128:ios:d5bd53f3dd865a5475dc0d',
    messagingSenderId: '379198043128',
    projectId: 'shift-c35b1',
    storageBucket: 'shift-c35b1.appspot.com',
    iosClientId:
        '379198043128-53nehpd76gdcqg4u07du110ne0lkrbk7.apps.googleusercontent.com',
    iosBundleId: 'com.brenden-smith.shift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjI9Z-LdL8IYLQtlqAStSoc9EW7fvLWKw',
    appId: '1:379198043128:ios:c789d1f27332956f75dc0d',
    messagingSenderId: '379198043128',
    projectId: 'shift-c35b1',
    storageBucket: 'shift-c35b1.appspot.com',
    iosClientId:
        '379198043128-0rbnm9i7eiig04b4gjqg736p2p8t97ro.apps.googleusercontent.com',
    iosBundleId: 'com.brenden-smith.shift.RunnerTests',
  );
}
